using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using Microsoft.Extensions.Logging;
using Signet.Core.Misc;

namespace Signet.App.Infrastructure;

/// <summary>
/// Applies the selected action icon set (<c>Default</c>/<c>Fluent</c>/<c>Material</c>/<c>Custom</c>
/// chosen in Preferences). The built-in sets are generated by the script
/// <c>scripts/generate-icon-themes.py</c> as <see cref="DrawingImage"/>s with their own
/// colors (multicolor <c>main</c> is the default; Fluent/Material use an accent color).
/// Icons are rendered through <c>ToolbarItemViewModel.IconKey</c> +
/// <see cref="IconKeyToImageConverter"/> in <c>MainWindow.axaml</c>.
/// </summary>
/// <remarks>
/// Changing the icon set requires a restart (the same pattern as
/// <see cref="LocalizationManager"/> and the appearance fields in Preferences) — simpler than
/// switching live resources for all open windows/dialogs at once.
///
/// The <c>custom</c> variant: instead of a built-in set, an <c>icons.json</c> file is loaded at
/// runtime (a map <c>{"icon-key": "SVG path data"}</c>, keys identical to those in
/// <c>FluentIcons.axaml</c>/<c>MaterialIcons.axaml</c>, values in the SVG path
/// mini-language parsed by <see cref="Geometry.Parse(string)"/>) from the folder
/// selected in Preferences. JSON (not an Avalonia <c>ResourceDictionary</c>) is a deliberate choice —
/// loading and compiling an arbitrary <c>.axaml</c> at runtime would require the additional
/// dependency <c>Avalonia.Markup.Xaml.Loader</c> (runtime XAML compiler), which is not used anywhere
/// else; a simple key→SVG path map covers the same use case without it.
/// The "Custom" set stays single-color (a <see cref="Geometry"/> rendered by
/// <c>PathIcon</c> in the text color) — the <c>icons.json</c> format does not carry colors.
/// </remarks>
public sealed class IconThemeManager(SettingsStore settings, ILogger<IconThemeManager> logger)
{
    private readonly SettingsStore _settings = settings;
    private readonly ILogger<IconThemeManager> _logger = logger;

    /// <summary>Supported icon sets (setting code + display name).</summary>
    public static readonly IReadOnlyList<(string Code, string DisplayName)> SupportedThemes =
        new[] { ("main", "Default"), ("fluent", "Fluent"), ("material", "Material"), ("custom", "Custom") };

    /// <summary>The current (normalized) icon set.</summary>
    public string Current => Normalize(_settings.UiIconTheme);

    /// <summary>Folder with the custom icon set (the "Custom" variant).</summary>
    public string CustomFolder
    {
        get => _settings.UiCustomIconFolder;
        set
        {
            _settings.UiCustomIconFolder = value;
            _settings.Save();
        }
    }

    /// <summary>Loads the saved icon set and merges it into the application resources.</summary>
    public void ApplySaved()
    {
        Apply(Current, _settings.UiCustomIconFolder);
        ApplyToolbarIconSize();
    }

    /// <summary>Application resource key holding the toolbar icon size (px).</summary>
    public const string ToolbarIconSizeResourceKey = "ToolbarIconSize";

    /// <summary>
    /// Toolbar icon size: the line height of the default font × <c>main_menu_icon_size</c>
    /// (1.8 by default), clamped to 12–48 px.
    /// </summary>
    public static int ComputeToolbarIconSize(double lineSpacing, double scaleFactor) =>
        Math.Clamp((int)(lineSpacing * scaleFactor), 12, 48);

    /// <summary>Recomputes the toolbar icon size after the UI font changes (live).</summary>
    public void RefreshToolbarIconSize() => ApplyToolbarIconSize();

    private void ApplyToolbarIconSize()
    {
        if (Application.Current is not { } app)
        {
            return;
        }

        double fontSize = app.TryFindResource("ControlContentThemeFontSize", out object? size) && size is double d
            ? d
            : 14;
        FormattedText probe = new(
            "Ag", System.Globalization.CultureInfo.InvariantCulture, FlowDirection.LeftToRight, Typeface.Default, fontSize, null);
        app.Resources[ToolbarIconSizeResourceKey] =
            (double)ComputeToolbarIconSize(probe.Height, _settings.MainMenuIconSize);
    }

    /// <summary>Persists the new icon set. The effect is visible only after the application restarts.</summary>
    public void Set(string themeCode)
    {
        string normalized = Normalize(themeCode);
        _settings.UiIconTheme = normalized;
        _settings.Save();
        _logger.LogInformation("Icon set saved as {IconTheme} (restart required)", normalized);
    }

    private void Apply(string themeCode, string customFolder)
    {
        if (Application.Current is not { } app)
        {
            return;
        }

        // Colored PNG icons — before the theme set so that "Custom" can override them
        // (a later merged dictionary takes precedence).
        app.Resources.MergedDictionaries.Add(LoadColoredIcons());

        ResourceDictionary? dictionary = themeCode == "custom"
            ? LoadCustomDictionary(customFolder)
            : LoadBuiltInDictionary(themeCode);

        if (dictionary is null)
        {
            if (themeCode == "custom")
            {
                // Empty/invalid folder — fall back to the default set instead of ending up without icons.
                dictionary = LoadBuiltInDictionary("main");
            }

            if (dictionary is null)
            {
                return;
            }
        }

        app.Resources.MergedDictionaries.Add(dictionary);
    }

    /// <summary>
    /// Keys of the icons that are not part of the theme sets — colored PNGs
    /// (<c>Assets/Icons/Calibre</c>), shared by all themes.
    /// </summary>
    public static readonly IReadOnlyList<string> ColoredIconKeys = new[] { "beautify", "html-fix", "polish" };

    /// <summary>Dictionary of the bitmaps for <see cref="ColoredIconKeys"/> (key = file name without <c>.png</c>).</summary>
    public static ResourceDictionary LoadColoredIcons()
    {
        ResourceDictionary dictionary = new();
        foreach (string key in ColoredIconKeys)
        {
            using Stream stream = AssetLoader.Open(new Uri($"avares://Signet.App/Assets/Icons/Calibre/{key}.png"));
            dictionary[key] = new Bitmap(stream);
        }

        return dictionary;
    }

    private static ResourceDictionary? LoadBuiltInDictionary(string themeCode)
    {
        string fileName = themeCode switch
        {
            "fluent" => "FluentIcons.axaml",
            "material" => "MaterialIcons.axaml",
            _ => "MainIcons.axaml",
        };
        Uri uri = new($"avares://Signet.App/Assets/Icons/{fileName}");
        return AvaloniaXamlLoader.Load(uri) as ResourceDictionary;
    }

    private ResourceDictionary? LoadCustomDictionary(string customFolder)
    {
        if (string.IsNullOrWhiteSpace(customFolder))
        {
            return null;
        }

        string path = Path.Combine(customFolder, "icons.json");
        if (!File.Exists(path))
        {
            _logger.LogWarning("Custom icon set: file {Path} not found, using the default set", path);
            return null;
        }

        try
        {
            string json = File.ReadAllText(path);
            Dictionary<string, string>? entries = JsonSerializer.Deserialize<Dictionary<string, string>>(json);
            if (entries is null || entries.Count == 0)
            {
                return null;
            }

            ResourceDictionary dictionary = new();
            foreach (KeyValuePair<string, string> entry in entries)
            {
                try
                {
                    dictionary[entry.Key] = Geometry.Parse(entry.Value);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Custom icon set: key {Key} skipped — invalid path data", entry.Key);
                }
            }

            return dictionary;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to load the custom icon set from {Path}", path);
            return null;
        }
    }

    private static string Normalize(string code) =>
        SupportedThemes.Any(t => string.Equals(t.Code, code, StringComparison.OrdinalIgnoreCase))
            ? code.ToLowerInvariant()
            : "main";
}
