using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AwesomeAssertions;
using Signet.Core.MiscEditors;
using Xunit;

namespace Signet.Core.Tests.MiscEditors;

/// <summary>Tests of <see cref="SavedSearchIo"/> and <see cref="SavedSearchStore"/>.</summary>
public sealed class SavedSearchIoTests
{
    private static readonly SearchEntry[] Sample =
    {
        new(IsGroup: true, "Grupa/", "Grupa", "", "", ""),
        new(IsGroup: false, "Grupa/Kot", "Kot", "kot", "pies", "NL DN CF"),
        new(IsGroup: false, "Prosty, z przecinkiem", "Prosty, z przecinkiem", "a", "b", "RX WR DN AH"),
    };

    [Fact]
    public void WriteJson_ThenReadJson_RoundTrips()
    {
        IReadOnlyList<SearchEntry> parsed = SavedSearchIo.ReadJson(SavedSearchIo.WriteJson(Sample));

        parsed.Should().BeEquivalentTo(Sample, o => o.WithStrictOrdering());
    }

    [Fact]
    public void ReadJson_InvalidContent_ReturnsEmpty()
    {
        SavedSearchIo.ReadJson("{ not json").Should().BeEmpty();
        SavedSearchIo.ReadJson("{}").Should().BeEmpty();
        SavedSearchIo.ReadJson(null).Should().BeEmpty();
    }

    [Fact]
    public void WriteDelimited_ThenReadDelimited_Tsv_RoundTripsLeaves()
    {
        SearchEntry[] leaves =
        {
            new(IsGroup: false, "Alfa", "Alfa", "f1", "r1", "NL DN CF"),
            new(IsGroup: false, "Beta/Gamma", "Gamma", "f2", "r2", "RX WR DN AH"),
        };

        string text = SavedSearchIo.WriteDelimited(leaves, '\t');
        IReadOnlyList<SearchEntry> parsed = SavedSearchIo.ReadDelimited(text, '\t', "import");

        parsed.Should().BeEquivalentTo(leaves, o => o.WithStrictOrdering());
    }

    [Fact]
    public void Csv_RoundTrips_ValuesContainingCommas()
    {
        SearchEntry[] leaves =
        {
            new(IsGroup: false, "Z przecinkiem", "Z przecinkiem", "a,b,c", "x,y", "NL DN CF"),
        };

        string csv = SavedSearchIo.WriteDelimited(leaves, ',');
        IReadOnlyList<SearchEntry> parsed = SavedSearchIo.ReadDelimited(csv, ',', "import");

        parsed.Single().Find.Should().Be("a,b,c");
        parsed.Single().Replace.Should().Be("x,y");
    }

    [Fact]
    public void ReadDelimited_EmptyNameField_GetsAutoGeneratedGroupedName()
    {
        IReadOnlyList<SearchEntry> parsed = SavedSearchIo.ReadDelimited("\tkot\tpies\tNL DN CF", '\t', "import");

        parsed.Single().FullName.Should().Be("import/rep00001");
    }

    [Fact]
    public void Store_SaveThenReloadWithNewInstance_PersistsEntries()
    {
        string path = System.IO.Path.Combine(
            System.IO.Path.GetTempPath(), $"signet-searches-{Guid.NewGuid():N}.json");
        try
        {
            new SavedSearchStore(path).Save(Sample);

            new SavedSearchStore(path).Load().Should().BeEquivalentTo(Sample, o => o.WithStrictOrdering());
        }
        finally
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }
    }

    [Fact]
    public void Store_Load_MissingFile_ReturnsEmpty()
    {
        new SavedSearchStore(System.IO.Path.Combine("nonexistent-dir", "missing.json"))
            .Load().Should().BeEmpty();
    }
}
