using System.Collections.Generic;
using Signet.Core.Localization;

namespace Signet.Core.MainUI;

/// <summary>A group in the curated special character grid.</summary>
public enum SpecialCharacterGroup
{
    /// <summary>Spaces and hyphens (the <c>spaces</c> group).</summary>
    Spaces,

    /// <summary>Punctuation and Latin-1 (the <c>characters</c> group).</summary>
    Common,

    /// <summary>Greek letters (the <c>characters2</c> group).</summary>
    Greek,

    /// <summary>Mathematical symbols and arrows (the <c>characters3</c> group).</summary>
    Symbols,
}

/// <summary>
/// A single entry of the curated "Insert Special Character" grid: the quadruple
/// <c>(insert text, display text, entity, description)</c>.
/// </summary>
/// <param name="Insert">The text inserted into the document (usually the character itself; for a few entries an entity, e.g. <c>&amp;amp;</c>).</param>
/// <param name="Display">The text on the button; empty = use <paramref name="Insert"/>.</param>
/// <param name="Entity">The named/numeric HTML entity (for tooltips and search).</param>
/// <param name="Description">A short description (for tooltips and search).</param>
/// <param name="Group">The group in the grid.</param>
public readonly record struct SpecialCharacterEntry(
    string Insert,
    string Display,
    string Entity,
    string Description,
    SpecialCharacterGroup Group)
{
    /// <summary>The text to show in the grid (Display or Insert, with a doubled <c>&amp;&amp;</c> collapsed to a single ampersand).</summary>
    public string DisplayText =>
        (string.IsNullOrEmpty(Display) ? Insert : Display).Replace("&&", "&", System.StringComparison.Ordinal);

    /// <summary>The translation key: the code points of the inserted text, e.g. <c>U+00AC</c>.</summary>
    public string Code => string.Join(
        "_",
        System.Linq.Enumerable.Select(Insert.EnumerateRunes(), r => "U+" + r.Value.ToString("X4", System.Globalization.CultureInfo.InvariantCulture)));

    /// <summary>The description in the interface language (the English <see cref="Description"/> when there is no translation).</summary>
    public string DisplayDescription => CatalogText.Description("SpecialChar", Code, Description);
}

/// <summary>
/// The curated special character grid for the "Insert Special Character" dialog
/// (the groups <c>spaces</c>, <c>characters</c>, <c>characters2</c>, <c>characters3</c>).
/// The full Unicode table is available through search by name
/// (<see cref="Semantics.CodepointNames.Search"/>).
/// </summary>
public static class SpecialCharacters
{
    /// <summary>All the grid entries, in display order.</summary>
    public static IReadOnlyList<SpecialCharacterEntry> Entries { get; } = new SpecialCharacterEntry[]
    {
            new(" ", "nbsp", "&nbsp;", "non-breaking space", SpecialCharacterGroup.Spaces),
            new(" ", "ensp", "&ensp;", "en space", SpecialCharacterGroup.Spaces),
            new(" ", "emsp", "&emsp;", "em space", SpecialCharacterGroup.Spaces),
            new(" ", "thinsp", "&thinsp;", "thin space", SpecialCharacterGroup.Spaces),
            new("&#173;", "shy", "&shy;", "soft hyphen", SpecialCharacterGroup.Spaces),
            new(" ", "nnbsp", "&#x202f;", "narrow non-breaking space", SpecialCharacterGroup.Spaces),
            new("‘", "", "&lsquo;", "left single quote", SpecialCharacterGroup.Common),
            new("’", "", "&rsquo;", "right single quote", SpecialCharacterGroup.Common),
            new("“", "", "&ldquo;", "left double quote", SpecialCharacterGroup.Common),
            new("”", "", "&rdquo;", "right double quote", SpecialCharacterGroup.Common),
            new("‹", "", "&lsaquo;", "left-pointing single angle quote", SpecialCharacterGroup.Common),
            new("›", "", "&rsaquo;", "right-pointing single angle quote", SpecialCharacterGroup.Common),
            new("«", "", "&laquo;", "left-pointing double angle quote", SpecialCharacterGroup.Common),
            new("»", "", "&raquo;", "right-pointing double angle quote", SpecialCharacterGroup.Common),
            new("'", "", "&apos;", "apostrophe", SpecialCharacterGroup.Common),
            new("\"", "", "&quot;", "double quote", SpecialCharacterGroup.Common),
            new("‚", "", "&sbquo;", "single low-9 quote", SpecialCharacterGroup.Common),
            new("„", "", "&bdquo;", "double low-9 quote", SpecialCharacterGroup.Common),
            new("—", "", "&mdash;", "em dash", SpecialCharacterGroup.Common),
            new("–", "", "&ndash;", "en dash", SpecialCharacterGroup.Common),
            new("§", "", "&sect;", "section sign", SpecialCharacterGroup.Common),
            new("¶", "", "&para;", "pilcrow - paragraph sign", SpecialCharacterGroup.Common),
            new("†", "", "&dagger;", "dagger", SpecialCharacterGroup.Common),
            new("‡", "", "&Dagger;", "double dagger", SpecialCharacterGroup.Common),
            new("&amp;", "&&", "&amp;", "ampersand", SpecialCharacterGroup.Common),
            new("&lt;", "<", "&lt;", "less-than sign", SpecialCharacterGroup.Common),
            new("&gt;", ">", "&gt;", "greater-than sign", SpecialCharacterGroup.Common),
            new("©", "", "&copy;", "copyright", SpecialCharacterGroup.Common),
            new("®", "", "&reg;", "registered sign", SpecialCharacterGroup.Common),
            new("™", "", "&trade;", "trademark symbol", SpecialCharacterGroup.Common),
            new("←", "", "&larr;", "left arrow", SpecialCharacterGroup.Common),
            new("→", "", "&rarr;", "right arrow", SpecialCharacterGroup.Common),
            new("•", "", "&bull;", "bullet", SpecialCharacterGroup.Common),
            new("·", "", "&middot;", "middle dot", SpecialCharacterGroup.Common),
            new("°", "", "&deg;", "degree sign", SpecialCharacterGroup.Common),
            new("±", "", "&plusmn;", "plus minus sign", SpecialCharacterGroup.Common),
            new("−", "", "&minus;", "minus sign", SpecialCharacterGroup.Common),
            new("×", "", "&times;", "multiplication sign", SpecialCharacterGroup.Common),
            new("÷", "", "&divide;", "division sign", SpecialCharacterGroup.Common),
            new("¼", "", "&frac14;", "fraction 1/4", SpecialCharacterGroup.Common),
            new("½", "", "&frac12;", "fraction 1/2", SpecialCharacterGroup.Common),
            new("¾", "", "&frac34;", "fraction 3/4", SpecialCharacterGroup.Common),
            new("⅓", "", "&#8531;", "fraction 1/3", SpecialCharacterGroup.Common),
            new("⅔", "", "&#8532;", "fraction 2/3", SpecialCharacterGroup.Common),
            new("⅛", "", "&#8539;", "fraction 1/8", SpecialCharacterGroup.Common),
            new("⅜", "", "&#8540;", "fraction 3/8", SpecialCharacterGroup.Common),
            new("⅝", "", "&#8541;", "fraction 5/8", SpecialCharacterGroup.Common),
            new("⅞", "", "&#8542;", "fraction 7/8", SpecialCharacterGroup.Common),
            new("…", "", "&hellip;", "horizontal ellipsis", SpecialCharacterGroup.Common),
            new("µ", "", "&micro;", "micron", SpecialCharacterGroup.Common),
            new("¢", "", "&cent;", "cent sign", SpecialCharacterGroup.Common),
            new("£", "", "&pound;", "pound sign", SpecialCharacterGroup.Common),
            new("€", "", "&euro;", "euro sign", SpecialCharacterGroup.Common),
            new("¿", "", "&iquest;", "inverted question mark", SpecialCharacterGroup.Common),
            new("¡", "", "&iexcl;", "inverted exclamation mark", SpecialCharacterGroup.Common),
            new("¨", "", "&uml;", "diaeresis", SpecialCharacterGroup.Common),
            new("´", "", "&acute;", "acute accent", SpecialCharacterGroup.Common),
            new("¸", "", "&cedil;", "cedilla", SpecialCharacterGroup.Common),
            new("ˆ", "", "&circ;", "circumflex accent", SpecialCharacterGroup.Common),
            new("˜", "", "&tilde;", "small tilde", SpecialCharacterGroup.Common),
            new("À", "", "&Agrave;", "capital A with grave", SpecialCharacterGroup.Common),
            new("Á", "", "&Aacute;", "capital A with acute", SpecialCharacterGroup.Common),
            new("Â", "", "&Acirc;", "capital A with circumflex", SpecialCharacterGroup.Common),
            new("Ã", "", "&Atilde;", "capital A with tilde", SpecialCharacterGroup.Common),
            new("Ä", "", "&Auml;", "capital A with diaeresis", SpecialCharacterGroup.Common),
            new("Å", "", "&Aring;", "capital A with ring above", SpecialCharacterGroup.Common),
            new("Æ", "", "&AElig;", "capital AE", SpecialCharacterGroup.Common),
            new("Ç", "", "&Ccedil;", "capital C with cedilla", SpecialCharacterGroup.Common),
            new("È", "", "&Egrave;", "capital E with grave", SpecialCharacterGroup.Common),
            new("É", "", "&Eacute;", "capital E with acute", SpecialCharacterGroup.Common),
            new("Ê", "", "&Ecirc;", "capital E with circumflex", SpecialCharacterGroup.Common),
            new("Ë", "", "&Euml;", "capital E with diaeresis", SpecialCharacterGroup.Common),
            new("Ì", "", "&Igrave;", "capital I with grave", SpecialCharacterGroup.Common),
            new("Í", "", "&Iacute;", "capital I with acute", SpecialCharacterGroup.Common),
            new("Î", "", "&Icirc;", "capital I with circumflex", SpecialCharacterGroup.Common),
            new("Ï", "", "&Iuml;", "capital I with diaeresis", SpecialCharacterGroup.Common),
            new("Ð", "", "&ETH;", "capital eth", SpecialCharacterGroup.Common),
            new("Ñ", "", "&Ntilde;", "capital N with tilde", SpecialCharacterGroup.Common),
            new("Ò", "", "&Ograve;", "capital O with grave", SpecialCharacterGroup.Common),
            new("Ó", "", "&Oacute;", "capital O with acute", SpecialCharacterGroup.Common),
            new("Ô", "", "&Ocirc;", "capital O with circumflex", SpecialCharacterGroup.Common),
            new("Õ", "", "&Otilde;", "capital O with tilde", SpecialCharacterGroup.Common),
            new("Ö", "", "&Ouml;", "capital O with diaeresis", SpecialCharacterGroup.Common),
            new("Ø", "", "&Oslash;", "capital O with stroke", SpecialCharacterGroup.Common),
            new("Œ", "", "&OElig;", "capital ligature OE", SpecialCharacterGroup.Common),
            new("Š", "", "&Scaron;", "capital S with caron", SpecialCharacterGroup.Common),
            new("Ù", "", "&Ugrave;", "capital U with grave", SpecialCharacterGroup.Common),
            new("Ú", "", "&Uacute;", "capital U with acute", SpecialCharacterGroup.Common),
            new("Û", "", "&Ucirc;", "capital U with circumflex", SpecialCharacterGroup.Common),
            new("Ü", "", "&Uuml;", "capital U with diaeresis", SpecialCharacterGroup.Common),
            new("Ý", "", "&Yacute;", "capital Y with acute", SpecialCharacterGroup.Common),
            new("Ÿ", "", "&Yuml;", "capital Y with diaeresis", SpecialCharacterGroup.Common),
            new("Þ", "", "&THORN;", "capital THORN", SpecialCharacterGroup.Common),
            new("ß", "", "&szlig;", "small sharp s", SpecialCharacterGroup.Common),
            new("à", "", "&agrave;", "small a with grave", SpecialCharacterGroup.Common),
            new("á", "", "&aacute;", "small a with acute", SpecialCharacterGroup.Common),
            new("â", "", "&acirc;", "small a with circumflex", SpecialCharacterGroup.Common),
            new("ã", "", "&atilde;", "small a with tilde", SpecialCharacterGroup.Common),
            new("ä", "", "&auml;", "small a with diaeresis", SpecialCharacterGroup.Common),
            new("å", "", "&aring;", "small a with ring above", SpecialCharacterGroup.Common),
            new("æ", "", "&aelig;", "small ae", SpecialCharacterGroup.Common),
            new("ç", "", "&ccedil;", "small c with cedilia", SpecialCharacterGroup.Common),
            new("è", "", "&egrave;", "small e with grave", SpecialCharacterGroup.Common),
            new("é", "", "&eacute;", "small e with acute", SpecialCharacterGroup.Common),
            new("ê", "", "&ecirc;", "small e with circumflex", SpecialCharacterGroup.Common),
            new("ë", "", "&euml;", "small e with diaeresis", SpecialCharacterGroup.Common),
            new("ì", "", "&igrave;", "small i with grave", SpecialCharacterGroup.Common),
            new("í", "", "&iacute;", "small i with acute", SpecialCharacterGroup.Common),
            new("î", "", "&icirc;", "small i with circumflex", SpecialCharacterGroup.Common),
            new("ï", "", "&iuml;", "small i with diaeresis", SpecialCharacterGroup.Common),
            new("ð", "", "&eth;", "small eth", SpecialCharacterGroup.Common),
            new("ñ", "", "&ntilde;", "small n with tilde", SpecialCharacterGroup.Common),
            new("ò", "", "&ograve;", "small o with grave", SpecialCharacterGroup.Common),
            new("ó", "", "&oacute;", "small o with acute", SpecialCharacterGroup.Common),
            new("ô", "", "&ocirc;", "small o with circumflex", SpecialCharacterGroup.Common),
            new("õ", "", "&otilde;", "small o with tilde", SpecialCharacterGroup.Common),
            new("ö", "", "&ouml;", "small o with diaeresis", SpecialCharacterGroup.Common),
            new("ø", "", "&oslash;", "small o with stroke", SpecialCharacterGroup.Common),
            new("œ", "", "&oelig;", "small ligature oe", SpecialCharacterGroup.Common),
            new("š", "", "&scaron;", "small s with caron", SpecialCharacterGroup.Common),
            new("ù", "", "&ugrave;", "small u with grave", SpecialCharacterGroup.Common),
            new("ú", "", "&uacute;", "small u with acute", SpecialCharacterGroup.Common),
            new("û", "", "&ucirc;", "small u with circumflex", SpecialCharacterGroup.Common),
            new("ü", "", "&uuml;", "small u with diaeresis", SpecialCharacterGroup.Common),
            new("ý", "", "&yacute;", "small y with acute", SpecialCharacterGroup.Common),
            new("ÿ", "", "&yuml;", "small y with diaeresis", SpecialCharacterGroup.Common),
            new("þ", "", "&thorn;", "small thorn", SpecialCharacterGroup.Common),
            new("ª", "", "&ordf;", "feminine ordinal indicator", SpecialCharacterGroup.Common),
            new("º", "", "&ordm;", "masculine ordinal indicator", SpecialCharacterGroup.Common),
            new("∞", "", "&infin;", "infinity", SpecialCharacterGroup.Common),
            new("Α", "", "&Alpha;", "Greek capital letter Alpha", SpecialCharacterGroup.Greek),
            new("α", "", "&alpha;", "Greek lower letter alpha", SpecialCharacterGroup.Greek),
            new("Β", "", "&Beta;", "Greek capital letter Beta", SpecialCharacterGroup.Greek),
            new("β", "", "&beta;", "Greek lower letter beta", SpecialCharacterGroup.Greek),
            new("Χ", "", "&Chi;", "Greek capital letter Chi", SpecialCharacterGroup.Greek),
            new("χ", "", "&chi;", "Greek lower letter chi", SpecialCharacterGroup.Greek),
            new("Δ", "", "&Delta;", "Greek capital letter Delta", SpecialCharacterGroup.Greek),
            new("δ", "", "&delta;", "Greek lower letter delta", SpecialCharacterGroup.Greek),
            new("Ε", "", "&Epsilon;", "Greek capital letter Epsilon", SpecialCharacterGroup.Greek),
            new("ε", "", "&epsilon;", "Greek lower letter epsilon", SpecialCharacterGroup.Greek),
            new("Η", "", "&Eta;", "Greek capital letter Eta", SpecialCharacterGroup.Greek),
            new("η", "", "&eta;", "Greek lower letter eta", SpecialCharacterGroup.Greek),
            new("Γ", "", "&Gamma;", "Greek capital letter Gamma", SpecialCharacterGroup.Greek),
            new("γ", "", "&gamma;", "Greek lower letter gamma", SpecialCharacterGroup.Greek),
            new("Ι", "", "&Iota;", "Greek capital letter Iota", SpecialCharacterGroup.Greek),
            new("ι", "", "&iota;", "Greek lower letter iota", SpecialCharacterGroup.Greek),
            new("Κ", "", "&Kappa;", "Greek capital letter Kappa", SpecialCharacterGroup.Greek),
            new("κ", "", "&kappa;", "Greek lower letter kappa", SpecialCharacterGroup.Greek),
            new("Λ", "", "&Lambda;", "Greek capital letter Lambda", SpecialCharacterGroup.Greek),
            new("λ", "", "&lambda;", "Greek lower letter lambda", SpecialCharacterGroup.Greek),
            new("Μ", "", "&Mu;", "Greek capital letter Mu", SpecialCharacterGroup.Greek),
            new("μ", "", "&mu;", "Greek lower letter mu", SpecialCharacterGroup.Greek),
            new("Ν", "", "&Nu;", "Greek capital letter Nu", SpecialCharacterGroup.Greek),
            new("ν", "", "&nu;", "Greek lower letter nu", SpecialCharacterGroup.Greek),
            new("Ω", "", "&Omega;", "Greek capital letter Omega", SpecialCharacterGroup.Greek),
            new("ω", "", "&omega;", "Greek lower letter omega", SpecialCharacterGroup.Greek),
            new("Ο", "", "&Omicron;", "Greek capital letter Omicron", SpecialCharacterGroup.Greek),
            new("ο", "", "&omicron;", "Greek lower letter omicron", SpecialCharacterGroup.Greek),
            new("Φ", "", "&Phi;", "Greek capital letter Phi", SpecialCharacterGroup.Greek),
            new("φ", "", "&phi;", "Greek lower letter phi", SpecialCharacterGroup.Greek),
            new("Π", "", "&Pi;", "Greek capital letter Pi", SpecialCharacterGroup.Greek),
            new("π", "", "&pi;", "Greek lower letter pi", SpecialCharacterGroup.Greek),
            new("″", "", "&Prime;", "Greek double prime", SpecialCharacterGroup.Greek),
            new("′", "", "&prime;", "Greek single prime", SpecialCharacterGroup.Greek),
            new("Ψ", "", "&Psi;", "Greek capital letter Psi", SpecialCharacterGroup.Greek),
            new("ψ", "", "&psi;", "Greek lower letter psi", SpecialCharacterGroup.Greek),
            new("Ρ", "", "&Rho;", "Greek capital letter Rho", SpecialCharacterGroup.Greek),
            new("ρ", "", "&rho;", "Greek lower letter rho", SpecialCharacterGroup.Greek),
            new("Σ", "", "&Sigma;", "Greek capital letter Sigma", SpecialCharacterGroup.Greek),
            new("σ", "", "&sigma;", "Greek lower letter sigma", SpecialCharacterGroup.Greek),
            new("Τ", "", "&Tau;", "Greek capital letter Tau", SpecialCharacterGroup.Greek),
            new("τ", "", "&tau;", "Greek lower letter tau", SpecialCharacterGroup.Greek),
            new("Θ", "", "&Theta;", "Greek capital letter Theta", SpecialCharacterGroup.Greek),
            new("θ", "", "&theta;", "Greek lower letter theta", SpecialCharacterGroup.Greek),
            new("Υ", "", "&Upsilon;", "Greek capital letter Upsilon", SpecialCharacterGroup.Greek),
            new("υ", "", "&upsilon;", "Greek lower letter upsilon", SpecialCharacterGroup.Greek),
            new("Ξ", "", "&Xi;", "Greek capital letter Xi", SpecialCharacterGroup.Greek),
            new("ξ", "", "&xi;", "Greek lower letter xi", SpecialCharacterGroup.Greek),
            new("Ζ", "", "&Zeta;", "Greek capital letter Zeta", SpecialCharacterGroup.Greek),
            new("ζ", "", "&zeta;", "Greek lower letter zeta", SpecialCharacterGroup.Greek),
            new("ℵ", "", "&alefsym;", "alef symbol", SpecialCharacterGroup.Symbols),
            new("∧", "", "&and;", "logical and", SpecialCharacterGroup.Symbols),
            new("∨", "", "&or;", "logical or", SpecialCharacterGroup.Symbols),
            new("∩", "", "&cap;", "intersection", SpecialCharacterGroup.Symbols),
            new("∪", "", "&cup;", "union", SpecialCharacterGroup.Symbols),
            new("≅", "", "&cong;", "congruent to", SpecialCharacterGroup.Symbols),
            new("↵", "", "&crarr;", "downwards arrow with corner leftwards", SpecialCharacterGroup.Symbols),
            new("¤", "", "&curren;", "currency sign", SpecialCharacterGroup.Symbols),
            new("⇓", "", "&dArr;", "downwards double arrow", SpecialCharacterGroup.Symbols),
            new("⇑", "", "&uArr;", "upwards double arrow", SpecialCharacterGroup.Symbols),
            new("↓", "", "&darr;", "downwards arrow", SpecialCharacterGroup.Symbols),
            new("↑", "", "&uarr;", "upwards arrow", SpecialCharacterGroup.Symbols),
            new("∅", "", "&empty;", "empty set", SpecialCharacterGroup.Symbols),
            new("≡", "", "&equiv;", "identical to", SpecialCharacterGroup.Symbols),
            new("∃", "", "&exist;", "there exists", SpecialCharacterGroup.Symbols),
            new("ƒ", "", "&fnof;", "Latin small letter f with hook", SpecialCharacterGroup.Symbols),
            new("∀", "", "&forall;", "for all", SpecialCharacterGroup.Symbols),
            new("⁄", "", "&frasl;", "fraction slash", SpecialCharacterGroup.Symbols),
            new("⇔", "", "&hArr;", "left right double arrow", SpecialCharacterGroup.Symbols),
            new("↔", "", "&harr;", "left right single arrow", SpecialCharacterGroup.Symbols),
            new("ℑ", "", "&image;", "black-letter capital I", SpecialCharacterGroup.Symbols),
            new("∫", "", "&int;", "integral", SpecialCharacterGroup.Symbols),
            new("∈", "", "&isin;", "element of", SpecialCharacterGroup.Symbols),
            new("⇐", "", "&lArr;", "leftwards double arrow", SpecialCharacterGroup.Symbols),
            new("⇒", "", "&rArr;", "double right arrow", SpecialCharacterGroup.Symbols),
            new("〈", "", "&lang;", "left-pointing angle bracket", SpecialCharacterGroup.Symbols),
            new("〉", "", "&rang;", "right-pointing angle bracket", SpecialCharacterGroup.Symbols),
            new("⌈", "", "&lceil;", "left ceiling", SpecialCharacterGroup.Symbols),
            new("⌉", "", "&rceil;", "right ceiling", SpecialCharacterGroup.Symbols),
            new("≤", "", "&le;", "less-than or equal to", SpecialCharacterGroup.Symbols),
            new("≥", "", "&ge;", "greater-than or equal to", SpecialCharacterGroup.Symbols),
            new("⌊", "", "&lfloor;", "left floor", SpecialCharacterGroup.Symbols),
            new("⌋", "", "&rfloor;", "right floor", SpecialCharacterGroup.Symbols),
            new("∗", "", "&lowast;", "asterisk operator", SpecialCharacterGroup.Symbols),
            new("◊", "", "&loz;", "lozenge", SpecialCharacterGroup.Symbols),
            new("¯", "", "&macr;", "macron", SpecialCharacterGroup.Symbols),
            new("∇", "", "&nabla;", "nabla", SpecialCharacterGroup.Symbols),
            new("≠", "", "&ne;", "not equal to", SpecialCharacterGroup.Symbols),
            new("∋", "", "&ni;", "contains as member", SpecialCharacterGroup.Symbols),
            new("¬", "", "&not;", "not sign", SpecialCharacterGroup.Symbols),
            new("∉", "", "&notin;", "not an element of", SpecialCharacterGroup.Symbols),
            new("⊄", "", "&nsub;", "not a subset of", SpecialCharacterGroup.Symbols),
            new("‾", "", "&oline;", "overline", SpecialCharacterGroup.Symbols),
            new("⊕", "", "&oplus;", "circled plus", SpecialCharacterGroup.Symbols),
            new("⊗", "", "&otimes;", "circled times", SpecialCharacterGroup.Symbols),
            new("∂", "", "&part;", "partial differential", SpecialCharacterGroup.Symbols),
            new("‰", "", "&permil;", "per mille sign", SpecialCharacterGroup.Symbols),
            new("⊥", "", "&perp;", "up tack", SpecialCharacterGroup.Symbols),
            new("ϖ", "", "&piv;", "Greek pi symbol", SpecialCharacterGroup.Symbols),
            new("∏", "", "&prod;", "n-ary product", SpecialCharacterGroup.Symbols),
            new("∝", "", "&prop;", "proportional to", SpecialCharacterGroup.Symbols),
            new("√", "", "&radic;", "square root", SpecialCharacterGroup.Symbols),
            new("ℜ", "", "&real;", "black-letter capital R", SpecialCharacterGroup.Symbols),
            new("⋅", "", "&sdot;", "dot operator", SpecialCharacterGroup.Symbols),
            new("ς", "", "&sigmaf;", "Greek small letter final sigma", SpecialCharacterGroup.Symbols),
            new("∼", "", "&sim;", "tilde operator", SpecialCharacterGroup.Symbols),
            new("⊂", "", "&sub;", "subset of", SpecialCharacterGroup.Symbols),
            new("⊃", "", "&sup;", "superset of", SpecialCharacterGroup.Symbols),
            new("⊆", "", "&sube;", "subset of or equal to", SpecialCharacterGroup.Symbols),
            new("⊇", "", "&supe;", "superset of or equal to", SpecialCharacterGroup.Symbols),
            new("∑", "", "&sum;", "n-ary summation", SpecialCharacterGroup.Symbols),
            new("¹", "", "&sup1;", "superscript one", SpecialCharacterGroup.Symbols),
            new("²", "", "&sup2;", "superscript two", SpecialCharacterGroup.Symbols),
            new("³", "", "&sup3;", "superscript three", SpecialCharacterGroup.Symbols),
            new("∴", "", "&there4;", "therefore sign", SpecialCharacterGroup.Symbols),
            new("ϑ", "", "&thetasym;", "Greek theta symbol", SpecialCharacterGroup.Symbols),
            new("ϒ", "", "&upsih;", "Greek Upsilon with hook symbol", SpecialCharacterGroup.Symbols),
            new("℘", "", "&weierp;", "script capital P", SpecialCharacterGroup.Symbols),
            new("¥", "", "&yen;", "yen sign", SpecialCharacterGroup.Symbols),
    };
}
